apiVersion: v1
kind: Service
metadata:
  name: utrains-service
spec:
  selector:
    app: utrains
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

# Create the service in the cluster 
# kubectl create -f my-first-service.yaml
#
# Check the service
# kubectl get svc
# kubectl get svc -o wide
#
# describe the service
# kubectl describe svc utrains-service
#
# delete the service
# kubectl delete svc utrains-service
