apiVersion: v1
kind: Service
metadata:
  name: utrains-service
spec:
  selector:
    name: utrains
  ports:
  - name: utrains-service-port
    protocol: TCP
    port: 80
    targetPort: 80

# This service is used to expose a pod previously created named utrains-pod
# since the type of service is not defined, by default it takes the ClusterIP type
# So the pod is only accessible inside the cluster
# create the service
# kubectl create -f service-def.yaml
#
# verify the objects created
# kubectl get pods
# kubectl get svc
# kubectl describe svc utrains-service
#
# Access the pod: This works only inside the cluster
# curl put-the-service-cluster-IP-here
#
# delete objects
# kubectl delete svc utrains-service
# kubectl delete pods utrains-pod
