apiVersion: v1
kind: Pod
metadata:
  name: utrains-pod
  labels:
    name: utrains
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80

# create a pod and expose it using a service
# kubectl create -f service-pod-def.yaml
#
# verify the objects created
# kubectl get pods
