apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

# Create the deployment in the cluster 
## kubectl create -f nginx-deployment.yaml
#
# Check the pods
## kubectl get pods
#
# Check the nodes where the pods are placed
## kubectl get pods -o wide
#
# check the deployments
## kubectl get deployment
#
# describe a pod
## kubectl describe pod pod-name-here
#
# describe the deployment
## kubectl describe deployment nginx-deployment
#
# delete the deployment
## kubectl delete deployment nginx-deployment
        
